services:
  webapp:
    image: nginx:${APP_VERSION:-latest}
    environment:
      - DEBUG=${DEBUG_MODE:-false}
      - APP_ENV=${NODE_ENV:-production}
      - CUSTOM_VAR=${CUSTOM_VALUE}

  backend:
    image: python:${PYTHON_VERSION:-3.11}-slim
    command: python -m http.server ${BACKEND_PORT:-8000}
    environment:
      - DEBUG=${DEBUG_MODE:-false}
      - DATABASE_URL=postgresql://${DB_USER:-user}:${DB_PASS:-pass}@db:5432/${DB_NAME:-app}
      - REDIS_URL=redis://cache:6379
    depends_on:
      - db
      - cache

  db:
    image: postgres:${POSTGRES_VERSION:-15}-alpine
    environment:
      - POSTGRES_DB=${DB_NAME:-app}
      - POSTGRES_USER=${DB_USER:-user}
      - POSTGRES_PASSWORD=${DB_PASS:-pass}

  cache:
    image: redis:${REDIS_VERSION:-alpine}
    command: redis-server --maxmemory ${REDIS_MEMORY:-100mb} --maxmemory-policy allkeys-lru
