services:
  app:
    image: busybox:uclibc
    command: ["httpd", "-f", "-p", "8080"]
    environment:
      INFRA_ENV: production
    init: true

  cache:
    image: busybox:uclibc
    command: ["httpd", "-f", "-p", "8080"]
    init: true
