services:
  app:
    extends:
      file: compose.base.yaml
      service: app
    environment:
      INFRA_ENV: development
      DEBUG: true
    init: true

  monitoring:
    image: busybox:uclibc
    command: ["httpd", "-f", "-p", "8080"]
    init: true
