services:
  webapp:
    image: busybox:${APP_VERSION:-uclibc}
    environment:
      DEBUG: ${DEBUG_MODE:-false}
      APP_ENV: ${APP_ENV:-production}
      CUSTOM_VAR: ${CUSTOM_VALUE}
    command: ["httpd", "-f", "-p", "8080"]
    init: true

  backend:
    image: busybox:${BACKEND_VERSION:-uclibc}
    environment:
      DEBUG: ${DEBUG_MODE:-false}
      DATABASE_URL: postgresql://${DB_USER:-user}:${DB_PASS:-pass}@db:5432/${DB_NAME:-app}
      REDIS_URL: redis://cache:6379
    depends_on:
      - db
      - cache
    command: httpd -f -p ${BACKEND_PORT:-8080}
    init: true

  cache:
    image: busybox:${REDIS_VERSION:-uclibc}
    command: ["httpd", "-f", "-p", "8080"]
    init: true

  db:
    image: busybox:${DB_VERSION:-uclibc}
    environment:
      LISTEN_PORT: ${DB_LISTEN_PORT:-24224}
      DB_ENV: ${DB_ENV:-production}
    command: ["httpd", "-f", "-p", "8080"]
    init: true
