services:
  web:
    image: busybox:uclibc
    environment:
      NGINX_ENV: production
    command: ["httpd", "-f", "-p", "8080"]
    init: true

  redis:
    image: busybox:uclibc
    command: ["httpd", "-f", "-p", "8080"]
    init: true
