include:
  - services/database.yaml
  - services/cache.yaml

services:
  api:
    image: python:3.11-slim
    command: python -m http.server 8000
    depends_on:
      - postgres
      - redis
    environment:
      - DATABASE_URL=postgresql://appuser:apppass@postgres:5432/appdb
      - REDIS_URL=redis://redis:6379
