services:
  app:
    image: node:18-alpine
    command: node -e "console.log('App running'); setInterval(() => {}, 1000)"
    environment:
      - NODE_ENV=production

  cache:
    image: redis:alpine
