include:
  - services/cache.yaml
  - services/logging.yaml

services:
  api:
    image: busybox:uclibc
    depends_on:
      - fluentbit
      - redis
    environment:
      FLUENTBIT_PORT: 24224
      REDIS_URL: redis://redis:6379
    command: ["httpd", "-f", "-p", "8080"]
    init: true
