services:
  web:
    environment:
      - NGINX_ENV=development
      - DEBUG=true

  db:
    image: postgres:15-alpine
    environment:
      - POSTGRES_DB=testdb
      - POSTGRES_USER=testuser
      - POSTGRES_PASSWORD=testpass
