include:
  - compose.base.yaml

services:
  app:
    extends:
      file: compose.base.yaml
      service: app
    environment:
      - NODE_ENV=development
      - DEBUG=app:*

  monitoring:
    image: prom/prometheus:latest
